name: Promote Python Package

on:
  repository_dispatch:
    types: [package_synchronized]

env:
  CLOUDSMITH_NAMESPACE: 'interview-vijay-yadav'
  CLOUDSMITH_SERVICE_SLUG: 'interview-cloud-smith'
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'prod'

permissions:
  id-token: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
        with:
          oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
          oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      - name: Extract dispatch payload
        id: payload
        run: |
          IDENTIFIER="${{ github.event.client_payload.identifier }}"
          PACKAGE_NAME="${{ github.event.client_payload.package_name }}"
          VERSION="${{ github.event.client_payload.version }}"

          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
            echo "âŒ No valid identifier received from dispatch payload."
            exit 1
          fi

          echo "Promoting package: $PACKAGE_NAME:$VERSION ($IDENTIFIER)"
          echo "identifier=$IDENTIFIER" >> $GITHUB_OUTPUT

      - name: Tag package as ready-for-production
        run: |
          IDENTIFIER="${{ steps.payload.outputs.identifier }}"
          cloudsmith tags add \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ready-for-production

      - name: Promote package to production
        run: |
          IDENTIFIER="${{ steps.payload.outputs.identifier }}"
          cloudsmith mv --yes \
            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
